server:
  port: ${ACTIVITY_SERVICE_PORT:8082}

spring:
  application:
    name: activity-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_ACTIVITY_DB:fitnessactivity}
      username: ${MONGODB_USERNAME:}
      password: ${MONGODB_PASSWORD:}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE:fitness.exchange}
  queue:
    name: ${RABBITMQ_QUEUE:activity.queue}
  routing:
    key: ${RABBITMQ_ROUTING_KEY:activity.tracking}