server:
  port: ${AI_SERVICE_PORT:8083}

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:fitnessrecommendation}
      database: ${MONGODB_DATABASE:fitnessrecommendation}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME:fitness.exchange}
  queue:
    name: ${RABBITMQ_QUEUE_NAME:activity.queue}
  routing:
    Key: ${RABBITMQ_ROUTING_KEY:activity.tracking}

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}