server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: fitness_user
    password: fitness_8279
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Make sure this is true for debugging
    properties:
      hibernate:
        format_sql: true # Make sure this is true for debugging
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost




