# docker-compose.yml
version: '3.8'

services:
  db: # This is the service name for PostgreSQL
    image: postgres:16-alpine
    restart: always # Keep the container running
    environment:
      POSTGRES_DB: fitness_user_db        # Your database name
      POSTGRES_USER: fitness_user    # Your database username
      POSTGRES_PASSWORD: fitness_8279 # Your database password
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      # This creates a named volume to persist your database data
      # So your data won't be lost if the container is removed
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Define the named volume